
export const addblogConstants={
    ADD_BLOG_REQUEST:'ADD_BLOG_REQUEST',
    ADD_BLOG_FAILED:'ADD_BLOG_FAILED',
    ADD_BLOG_SUCCESS:'ADD_BLOG_SUCCESS',
    GET_BLOG_REQUEST:'GET_BLOG_REQUEST',
    GET_BLOG_FAILED:'GET_BLOG_FAILED',
    GET_BLOG_SUCCESS:'GET_BLOG_SUCCESS',
    GET_ISP_DETAILS_REQUEST:'GET_ISP_DETAILS_REQUEST',
    GET_ISP_DETAILS_FAILED:'GET_ISP_DETAILS_FAILED',
    GET_ISP_DETAILS_SUCCESS:'GET_ISP_DETAILS_SUCCESS',
}
